# for all time 0 <= t < N, calculate simulated values of X^t_u and M^t_u (fictitious evolution of personal and account values if GLWB is initiated at t) for u>=t, given initial values Xt, Mt and simulated returns dS_S. Use this values to calculate Ft, present value at t of all future cash-flows generated by a contract that has been initiated at t.

# nsim: number of simulations, a scalar
# Xt: simulated values of the personal account, an (N x nsim) matrix
# Mt: simulated values of the personal account, , an (N x nsim) matrix
# dS_S: an (N x nsim) - matrix with the simulated log returns of the reference fund 
# N: the number of periods, a scalar (integer)
# d: the time step (a fraction of year)
# psi: the management fee
# phi: the insurance fee
# beta: the roll-up rate (= 0 in this case)
# gt: the annuity rate if GLWB is initiated at t, a scalar
# tau: a vector of time of deaths (integers) of length nsim
# B: : an (N x nsim) - matrix with the simulated (or calculated) discount factors

calculate_F <- function(nsim, X, M, dS_S, psi, phi, beta = 0, gt, tau, Nbar, B)
{
  FF <- matrix(0, nrow = Nbar, ncol = nsim)
  gt <- rep(gt, length.out = Nbar)
  
  for(t in 0 : (Nbar - 1))
  {
    F_temp <- rep(0, times = nsim)

    X0 <- X[t + 1, ]
    M0 <- M[t + 1, ]

    for(u in (t + 1) : Nbar)
    {
      X1 <- pmax(X0 * (1 + dS_S[u, ] - psi) - (phi + gt[t + 1]) * M0, 0)
      M1 <- pmax(M0 * (1 + beta), X1)
      
      F_temp <- F_temp + (gt[t + 1] * M0 * (tau >= u) + X1 * (tau == u)) * (B[t + 1, ] / B[u + 1, ])
      
      X0 <- X1
      M0 <- M1
    }
    FF[t + 1, ] <- F_temp
  }
  return(FF)
}