calculate_F <- function(nsim, Xt, Mt, dS_S, N, d = 1, psi, phi, beta = 0, gt, tau, B)
{
  # for all time 0 <= t < N, calculate simulated values of X^t_u and M^t_u (fictitious evolution of personal and account values if GLWB is initiated at t) for u>=t, given initial values Xt, Mt and simulated returns dS_S. Use this values to calculate Ft, present value at t of all future cash-flows generated by a contract that has been initiated at t.
  
  # nsim: number of simulations, a scalar
  # Xt: simulated values of the personal account, an (N x nsim) matrix
  # Mt: simulated values of the personal account, , an (N x nsim) matrix
  # dS_S: an (N x nsim) - matrix with the simulated log returns of the reference fund 
  # N: the number of periods, a scalar (integer)
  # d: the time step (a fraction of year)
  # psi: the management fee
  # phi: the insurance fee
  # beta: the roll-up rate (= 0 in this case)
  # gt: the annuity rate if GLWB is initiated at t, a scalar
  # tau: a vector of time of deaths (integers) of length nsim
  # B: : an (N x nsim) - matrix with the simulated (or calculated) discount factors
  
  F0N <- matrix(0, nrow = N, ncol = nsim)
  rownames(F0N) <- 0 : (N - 1)
  
  for(t in 0 : (N - 1))
  {
    Ft <- rep(0, times = nsim)
    # set up vector for Ft
    
    Xt0 <- Xt[t + 1, ]
    Mt0 <- Mt[t + 1, ]
    # starting values for X^t and M^t
    
    for(j in (t + 1) : N)
    {
      # calculates new values for X^t and M^t from old ones, update iteratively Ft then assign new value to X^t, M^t
      # j = current period
      
      Xt1 <- pmax(Xt0 * (1 + dS_S[j, ] - psi * d) - (phi + gt) * d * Mt0, 0)
      Mt1 <- pmax(Mt0 * (1 + beta * d), Xt1)
      
      Ft <- Ft + (gt * d * Mt0 * (tau >= j) + Xt1 * (tau == j)) * (B[t + 1, ] / B[j + 1, ])
      
      Xt0 <- Xt1
      Mt0 <- Mt1
    }
    
    F0N[t + 1, ] <- Ft
    
  }
  
  return(F0N)
}
